spring.application.name=UserAuthService

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/userdb
spring.datasource.username=userdb_1
# spring.datasource.password=Gowda@1897